### ISSUE TITLE
Create email and password field in the login page for users to enter their email and password(Figma wireframe task)

### ISSUE THREAD

**Issue by zechen31** [cse442-at-ub/project_s23-team-infinity#1]
**Task tests**

*Test 1*
1) Open the webpage
2) Verify that it's in the login page
3) Verify that there are two fields one is email and another one is password

https://www.figma.com/file/uwldPFPAEUZsxTFz8ZwkoB/Homepage?node-id=0%3A1&t=D9qSRAOWsPcj43bt-1

**Comment by ShawnManivong** [comment]
link figma
