### ISSUE TITLE
Create a Login page in React based off Figma

### ISSUE THREAD

**Issue by xuanpuzh** [cse442-at-ub/project_s23-team-infinity#11]
**Task Test**

*Test 1*

1) Install the React environment.
2) Try the js syntax.
3) Learn the components of React.
4) Try to write a simple login page with React.

*Test 2*
1) Verify the code in App.js and match every component on website with the code by inspecting.(right click the webpage).
2) Compare the website with Figma prototype to make sure all of the features are created.

Figma: https://www.figma.com/file/uwldPFPAEUZsxTFz8ZwkoB/Homepage?node-id=0%3A1&t=3ZIZs0TPkRDjzVSR-0

**Comment by ShawnManivong** [comment]
please add assignees and  sprint number

**Comment by ShawnManivong** [comment]
please link figma
