### ISSUE TITLE
As a user who is going to use the calendar everyday, I want to the application to remember my account so that I won't need to type in my account and password every times

### ISSUE THREAD

**Issue by TheRealColeG** [cse442-at-ub/project_s23-team-infinity#12]
**Acceptance tests**

*Test 1*

1) Go to the page : https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442ad/
2) Register the account with an account example@buffalo.edu and password "password"
3) Click the login under the register page
4) Enter account example@buffalo.edu and password "password"
5) Click login 
6) Verify you are redirect to another page
7) Go to the page (https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442ad/) again
8) Verify you are in the login page.

*Test 2*

1) Go to the page : https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442ad/
2) Register the account with an account example@buffalo.edu and password "password"
3) Click the login under the register page
4) Enter account example@buffalo.edu and password "password"
5) Verify there is checkbox called "remember me"
6) Check the checkbox
7) Click login 
8) Verify you are redirect to another page
9) Go to the page (https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442ad/) again
10) Verify you are not in the login page but the homepage.

**Comment by ShawnManivong** [comment]
there should be a blank line between each test.
