### ISSUE TITLE
As an employee, I want to add a meeting/event I have to my calendar so when I use the application I could know I have a meeting/event upcoming.

### ISSUE THREAD

**Issue by danielleakosua** [cse442-at-ub/project_s23-team-infinity#14]
**Acceptance Tests:**

*Test 1*

1) Go to the website (https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442ad/)
2) Login with your account, if you don't have an account, register one
3) Verify you are redirect to another page
4) Verify there is a button called "create event" in the left side of the page.
5) Click the button
6) Verify there is a new window pops out
7) Type the title of your event/meeting
e" field
8) Verify you can choose start time
9) Verify you can choose end time
10) Verify there is a filed for you to enter a location under the time
11) Type a location you want
12) Verify you can add details in the bottom of the field
13) Verify there is  a save button in the bottom right corner
14) Click the save button
15) Verify you are back to the home page
16) Verify there is a calendar in the left side of the page
17) Go to the date that you choose for the event/meeting you just created
18) Verify there is a schedule in the left side of the page
19) Verify the schedule has the date you just picked
20) Verify you event shows successfully in the left side of the schedule

**Comment by ShawnManivong** [comment]
Write "Acceptance tests" in bold as the start of this text.

 there should be a blank line between each test.
