### ISSUE TITLE
Create a Hello World page by using React.js and PHP

### ISSUE THREAD

**Issue by zechen31** [cse442-at-ub/project_s23-team-infinity#15]
**Task Test**

*Test 1*

1) run 'npm start' command in the directory
2) Verify that a webpage is running on localhost:3000 by default
3) Verify that there is a field to enter your name and a submit button
4) Type your name in the field
5) Verify that it holds the functionality of typing in the field
6) Hit submit button
7) Verify that your name shows on the screen properly with the welcome message
8) Type another name and verity that the message shows correctly with the name you type in the second time.

**Comment by ShawnManivong** [comment]
link github
