### ISSUE TITLE
Create login field in the login page that redirects to the home page(Figma wireframe task)

### ISSUE THREAD

**Issue by zechen31** [cse442-at-ub/project_s23-team-infinity#2]
**Task tests**

*Test 1*

1) Open the webpage
2) Verify that the page shows as login page
3) Verify that there is a button labeled "login"
4) Click login
5) Verify that the page redirects to the home page

https://www.figma.com/file/uwldPFPAEUZsxTFz8ZwkoB/Homepage?node-id=0%3A1&t=D9qSRAOWsPcj43bt-1

**Comment by ShawnManivong** [comment]
link figma
