### ISSUE TITLE
As a user who wants to use this application, I want to be able to login via email and password I created so that I can use this application at any times and places

### ISSUE THREAD

**Issue by zechen31** [cse442-at-ub/project_s23-team-infinity#22]
**Acceptance Test**

*Test 1*

1) Go to the website that is provided (https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442ad/)
2) Verify that there are two field on the left side of the page called email and password
3) Enter correct email and password
4) Verify that there is a button called "Login" under the password field
5) Click login button
6) Verify that your page redirects to the home page

*Test 2*

1) Go to the website that is provided (https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442ad/)
2) Verify that there are two boxes on the left side of the page called email and password
3) Enter wrong email and password
4) Verify that there is a button called "Login" under the password field
5) Click login button
6) Verify that there is an error message pops out 
7) Verify that your page does not change to the home page

**Comment by ShawnManivong** [comment]
there should be a blank line between each test.

**Comment by ShawnManivong** [comment]
remove developer lingo "two field on the left side"
