### ISSUE TITLE
Create forgot password field in the login page that redirects to the page for users to reset their password(Figma Wireframe task)

### ISSUE THREAD

**Issue by zechen31** [cse442-at-ub/project_s23-team-infinity#3]
**Task tests**

*Test 1*

1) Open the webpage
2) Verify that there is a button labeled "Forgot password" in red.
3) Click the "Forgot password" button and verify that the page redirects to another page called "forgot password"

https://www.figma.com/file/uwldPFPAEUZsxTFz8ZwkoB/Homepage?node-id=0%3A1&t=D9qSRAOWsPcj43bt-1

**Comment by ShawnManivong** [comment]
link figma
