### ISSUE TITLE
As a client with important events pertaining to myself, I want to be able to create an account so that I can be solely associated with that account (my name, email, and password).

### ISSUE THREAD

**Issue by TheRealColeG** [cse442-at-ub/project_s23-team-infinity#30]
Acceptance Tests
--------------
1. Attempt to create *multiple* valid accounts and be sure that they are all created with proper credentials
2. Attempt to create *multiple* invalid accounts which includes:
     - Username already in use
     - Email already in use
     - Empty username/email/password
     - Any/all combinations of the above three
     These should **all** result in account creation failure
3. Assure that after closing and reopening application, successfully created accounts still accessible and visible

**Comment by ShawnManivong** [comment]
there should be a blank line between each test.

remove task labels input/output blocks (just need acceptance tests)

Add dependencies
