### ISSUE TITLE
As a client with an account, I want to be able to log in to the account that I created so that I can create events only I can see.

### ISSUE THREAD

**Issue by TheRealColeG** [cse442-at-ub/project_s23-team-infinity#31]
Acceptance Testing
--------------------
1. Register multiple accounts
3. Attempt to log in to all accounts created
4. For all accounts created, attempt logging in with incorrect password
5. Furthermore, attempt logging in with nonexistent usernames/emails
6. After logging in, verify that events associated with the user signed in appear (AND ONLY THAT USER'S EVENTS)

**Comment by ShawnManivong** [comment]
there should be a blank line between each test.

remove task labels input/output blocks (just need acceptance tests)

Add dependencies
