### ISSUE TITLE
Create a Sign Up front-end page in React

### ISSUE THREAD

**Issue by xuanpuzh** [cse442-at-ub/project_s23-team-infinity#32]
**Task tests**

*Test 1*
1) Go to the React project folder and launch the web pages using "npm start"
2) Verify that there is a SignUp page for users to create accounts.
3) Verify there are 4 inputs and each for "username", "email", "password" and "confirm password".
4) Type in the text for each box to verify each input boxes works
5) Verify there is a SignUp button at bottom.
6) Verify there is a "Already have an account? Login" button linked to Login Page.
7) Click the "Already have an account? Login" button to verify the login page shows up.
8) Right click the webpage and go to inspect model to check all elements in SignUp align the React JSX code.

*Test 2*
1) Go  to "cse442-project/src" folder
2) Check the pages folder that used to save React script of web pages.
3) Verify there is a SignUp.js script.
4) Go to "cse442-project/package.json" file and check the packages that used for SignUp page, "styled-commponent" and "react-router-dom", are in it.

**Comment by ShawnManivong** [comment]
Write "Task tests" in bold as the start of this text.

Each task test must be labeled and there should be a blank line between each test.
