### ISSUE TITLE
Create documentation for possible local storage

### ISSUE THREAD

**Issue by TheRealColeG** [cse442-at-ub/project_s23-team-infinity#33]
***Task Tests***
---------------
1. Research about possible local storage options
2. Discuss possibilities and give pros and cons to each option
3. Choose the best option and give a brief description and how-to for the best option
4. Store all of this in a google docs for easy reading for all group mates (and any possible new members)
https://docs.google.com/document/d/151L9N6WUazXOJ3_t3JYLuxgHhmbUL9T0j9TUNssW3Fg/edit?usp=drivesdk

**Comment by ShawnManivong** [comment]
Still requires task/task tests format 

Add assignees

**Comment by ShawnManivong** [comment]
Still requires task/task tests format 

Add assignees
