### ISSUE TITLE
Create a design of the calendar (Figma wireframe)

### ISSUE THREAD

**Issue by zechen31** [cse442-at-ub/project_s23-team-infinity#34]
**Task Test**

*Test 1*

1) Go the link of the figma that is provided (https://www.figma.com/file/uwldPFPAEUZsxTFz8ZwkoB/Homepage?node-id=0%3A1&t=xQqgdnKRc8Qv1cMi-1)
2) Verify there is a present button in the top right corner next to "share"
3) Click the present button
4) Verify you are in the login page that has a login button in the left side of the page
5) Click the login button
6) Verify the page redirects to another page
7) Verify this page has a calendar in the left middle of the page 
8) Click the calendar
9) Verify the page redirects to the page with a few pictures about the calendar

**Comment by ShawnManivong** [comment]
there should be a blank line between each test.
