### ISSUE TITLE
Create the functionality for the user to reset password 

### ISSUE THREAD

**Issue by zechen31** [cse442-at-ub/project_s23-team-infinity#41]
**Task Test**

*Test 1*

1) Go to the server
2) Verify that there is login button in the left of the page
3) Verify that there is a link called "forgot password" in the top right corner of the login button
4) Click the "forgot password" button
5) Verify the page redirects to another page
6) Verify there is a title called "Forgot password" in the middle of the page
7) Verify there is a subtitle "Email" and a field under the "Forgot password" title
8) Type your email that matched the account that you need to reset password
9) Click the "Reset password" button under the text field
10) Verify you get the an email verification 
11) Verify the page redirects to another page
12) Verify there is a message called "enter the 6 digit code we sent to your email to reset password"
13) Enter the code you received
14) Click the verify button under the text field
15) Verify the page redirects to another page
16) Verify there is three fields for you to enter your username/email, password and confirm password
17) Enter the username/email that match to the email that get the verification code
18) Enter new password and confirm password
19) Click the Reset button under in the bottom of the page
20) Verify the page redirects to the home page
21) Login with username and the new password
22) Verify you login in successfully

*Test 2*

1) Go to the server
2) Verify that there is login button in the left of the page
3) Verify that there is a link called "forgot password" in the top right corner of the login button
4) Click the "forgot password" button
5) Verify the page redirects to another page
6) Verify there is a title called "Forgot password" in the middle of the page
7) Verify there is a subtitle "Email" and a field under the "Forgot password" title
8) Type your email that matched the account that you need to reset password
9) Click the "Reset password" button under the text field
10) Verify you get the an email verification 
11) Verify the page redirects to another page
12) Verify there is a message called "enter the 6 digit code we sent to your email to reset password"
13) Enter the code you received
14) Click the verify button under the text field
15) Verify the page redirects to another page
16) Verify there is three fields for you to enter your username/email, password and confirm password
17) Enter the username/email that match to the email that get the verification code
18) Enter new password and confirm password
19) Click the Reset button under in the bottom of the page
20) Verify the page redirects to the home page
21) Login with username and the old password
22) Verify there is an error message pops out saying wrong password

**Comment by ShawnManivong** [comment]
there should be a blank line between each test.
