### ISSUE TITLE
Create add functionality for events

### ISSUE THREAD

**Issue by TheRealColeG** [cse442-at-ub/project_s23-team-infinity#42]
***TASK TESTS***
-------------------------------

***Pretest Requirements***
-------------------------------
1. Go to cheshire directory -> backend (index.php should display with "Register" and "Create Event"
2. Create a user if one hasn't been done already (REMEMBER THE USERNAME)

**Test 1** - Works with correct inputs
------------------------------------------
1. Create a typical event with username just registered above
2. Verify that the phpMyAdmin updates the Events table with event just added (with correct userID corresponding to username [found in Users table])

**Test 2** - Does *not* work with incorrect inputs
---------------------------------------------------
1. Create event with random username (anything that isn't in the Users table)
2. Verify that phpMyAdmin does not show the event that was just attempted
3. Create event with no title
4. Verify that phpMyAdmin does not show the event that was just attempted

**Test 3** - Resists SQL Injection attacks
---------------------------------------------
1. Create event with SQL injection attack embedded within some field
2. Verify that phpMyAdmin updates accordingly (Creates the event with the field if the username was legal or does not create the event if illegal username)
3. Secondly, verify that the SQL injection was not executed.

**Comment by ShawnManivong** [comment]
there should be a blank line between each test.
