### ISSUE TITLE
Create SignIn and SignUp front-end functionality

### ISSUE THREAD

**Issue by xuanpuzh** [cse442-at-ub/project_s23-team-infinity#43]
**Task test**

*Test 1*

1) Go to the Login webpage:https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442ad/
2) Verify the Login button at left bottom.
3) Verify there are 2 inputs: Username/email and password.
4) Verify the remember me checkbox works.
5) Click the login button to verify the alert error when the php server is off.
6) Click the login button to verify php server response if php server is on.
7) Click "signup" text to verify it directs to login page.
8) Click "forgot password" text to verify it directs to login page.

*Test 2*
1) Go to SignUp page:https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442ad/signup
2) Verify the SignUp button is at bottom.
3) Verify there are 4 input boxes: "Username", "email address", "password", and "confirm password".
4) Check SignUp button returns error when php server is off.
5) Click the signup button to verify php server response if php server is on.
6) Click "login" text to verify it directs to login page.

**Comment by ShawnManivong** [comment]
Add sprint label

 there should be a blank line between each test.

Write "Task tests" in bold as the start of this text.
