### ISSUE TITLE
Syntax Tasks

### ISSUE THREAD

**Issue by duncenzh** [cse442-at-ub/project_s23-team-infinity#6]
**Task Test**

*Test 1*
1) Print Hello World in php
2) Check if Hello World was printed:
3) Loop and print number 1 to 10 in php
4) Check if all numbers have been printed
5) Created a function that when called with parameters of 2 numbers will add then compare if it is greater than 10 and print out yes or no
6) Input: 3 and 4, Output: no
7) Input: 5 and 6 Output: yes

**Comment by ShawnManivong** [comment]
please add assignees and  sprint number

**Comment by ShawnManivong** [comment]
link github
