### ISSUE TITLE
Settle the basic environment for React.js

### ISSUE THREAD

**Issue by zechen31** [cse442-at-ub/project_s23-team-infinity#7]
**Task Test**

*Test 1*
1) Install Node.js and NPM (Node Package Manager)
2) Create a basic app name 'my-app' by running 'npx create-react-app my-app' command in the terminal
3) Open the directory by running 'cd my-app' command
4) start the app by running 'npm start' command, default hosted at localhost:3000

**Comment by ShawnManivong** [comment]
please add assignees and  sprint number
